### ISSUE TITLE
Wrong percentage on Relic Total HP/s as %

### ISSUE THREAD

**Issue by Scolal** [VashCowaii/r2_loadout_calc#2]
![image](https://github.com/VashCowaii/r2_loadout_calc/assets/15338124/3443c3df-2d69-4d6d-9a07-ff2d7abb83bb)
I belive the percentage should be 2,44%, looks like a double applied /100 for the percentage to me, but i may be wrong.
The calculator is awesome btw, i really enjoy it, sorry if this is the wrong channel to contact you.

**Comment by VashCowaii** [comment]
No worries, it's no bother, this place is fine to let me know.

Do you mind linking the build? If you post the URL, it will contain everything that was selected, which will help me better understand what is happening here.

**Comment by VashCowaii** [comment]
Scratch that, I found the issue.
`updateDisplay("advancedRelicTotal%",(advancedRelicPerc + advancedRelicFlat/totalHealth),2,"%");`
It should be:
`updateDisplay("advancedRelicTotal%",(advancedRelicPerc + advancedRelicFlat/totalHealth)*100,2,"%");`
Thankfully, though, this was ONLY for that specific row, it didn't actually screw up any values, so the end total "as flat" or "as %" are still correct, thank god for that lol.

Thank you for pointing this out! I'll have that fixed here later today!

**Comment by Scolal** [comment]
Sorry, i just saw the reply =\
Happy to be of help =)

**Comment by VashCowaii** [comment]
Github is really struggling with deployments today, I sent it over an hour ago now and it still hasn't happened yet. Gonna leave this open until I can verify that the fix went through.

**Comment by VashCowaii** [comment]
Looks like it finally went through, we're set. Lmk if you have any other problems in the future, under a new post.

**Comment by VashCowaii** [comment]
Lmfao scratch that, there were some value issues on relic related end displays. Fixing them right now

**Comment by VashCowaii** [comment]
Alright I've deployed a fix for it. Dunno how long github will take to deploy it, but I'm probably gonna head to bed, hopefully we're actually set now lol.
